5-2-add-buttons-screens
D-Golovanov/surf-flutter-course-golovanov pull request #16
Opened 2023-04-16 19:50 UTC by D-Golovanov

2023-04-24 23:04 UTC, D-Golovanov commented
![Screenshot_20230425-020120](https://user-images.githubusercontent.com/43075263/234134349-6c9698d6-0c20-492a-9d72-a5976b24ee34.png)
![Screenshot_20230425-020007](https://user-images.githubusercontent.com/43075263/234134355-3f30961a-9a63-4f9f-b10a-ee4448d7cefa.png)
![Screenshot_20230425-015950](https://user-images.githubusercontent.com/43075263/234134358-be594915-79a9-461f-836a-80532a191701.png)

2023-04-25 16:14 UTC, egrischenkov requested changes
По коду кажется все хорошо! За исключением двух вещей.
 1. мне не нравится монструозный метод _findPlaceFilter на экране фильтров. Предлагаю его декомпозировать. И не очень понимаю задумку с разными списками для разного типа мест. И также не очень понятна конструкция if else  в конце, ведь независимо от условия она выполни одну и ту же операцию. Может я что то не углядел, можно разъяснить пожалуйста?
 2. Закомментированный кусок в _ImageCardWidget лучше убрать если уже не нужен.
 
 Также есть пару замечаний по дизайну. Когда мы переходим на экране фильтров bottom navigation bar не должен быть виден. Также на экране отсутствует кнопка возвращения назад.

2023-04-27 20:23 UTC, D-Golovanov commented
1. _findPlaceFilter переписал, но все равно не смог избавиться от if else, не могу придумать как отфильтровать за 1 проход если выбраны фильтры (то получается вызывается метод по вхождению в радиус и условие что тип соответствует фильтру), а else просто ищет вхождение в радиус.
2. все ненужное, вроде, почистил +разнес экран и виджеты, чтобы полегче воспринимать.
3. на экране фильтров же нет боттом бара)

2023-04-28 17:13 UTC, egrischenkov commented
Хмм. Магия) В тот раз запускал был. но да ладно)

2023-04-28 17:13 UTC, egrischenkov approved these changes

2023-05-02 17:33 UTC, merged